<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
  
    <link rel="shortcut icon" href="../assets/img/titleem.ico">
    <link href="../vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="../js/alertifyjs/css/alertify.css" rel="stylesheet" type="text/css">
    <script type="text/javascript" src="../js/funciones.js"></script>
    
   

    <link rel="stylesheet" type="text/css" href="../dependencias/DataTables-1.10.22/css/jquery.dataTables.css"/>
<link rel="stylesheet" type="text/css" href="../dependencias/Buttons-1.6.4/css/buttons.dataTables.css"/>
<link rel="stylesheet" type="text/css" href="../dependencias/Responsive-2.2.6/css/responsive.dataTables.css"/>
<link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="../css/sb-admin-2.min.css" rel="stylesheet">
  
 
<script type="text/javascript" src="../dependencias/JSZip-2.5.0/jszip.js"></script>
<script type="text/javascript" src="../js/alertifyjs/alertify.min.js"></script>
<script type="text/javascript" src="../dependencias/pdfmake-0.1.36/pdfmake.js"></script>
<script type="text/javascript" src="../dependencias/pdfmake-0.1.36/vfs_fonts.js"></script>
<script type="text/javascript" src="../dependencias/DataTables-1.10.22/js/jquery.dataTables.js"></script>
<script type="text/javascript" src="../dependencias/Buttons-1.6.4/js/dataTables.buttons.js"></script>
<script type="text/javascript" src="../dependencias/Buttons-1.6.4/js/buttons.colVis.js"></script>
<script type="text/javascript" src="../dependencias/Buttons-1.6.4/js/buttons.flash.js"></script>
<script type="text/javascript" src="../dependencias/Buttons-1.6.4/js/buttons.html5.js"></script>
<script type="text/javascript" src="../dependencias/Buttons-1.6.4/js/buttons.print.js"></script>
<script type="text/javascript" src="../dependencias/Responsive-2.2.6/js/dataTables.responsive.js"></script>

 <script type="text/javascript" src="../js/popper.js"></script>